services:
  - type: web
    name: sigmel
    env: node
    plan: free
    region: oregon
    buildCommand: |
      npm install
      cd frontend && npm install && npm run build
      cd ..
      xcopy frontend\dist backend\public /E /H /Y
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
