services:
  - type: web
    name: sigmel
    env: node
    region: oregon
    buildCommand: |
      npm install
      cd frontend
      npm install
      npm run build
      xcopy dist "..\backend\public" /E /H /Y
    startCommand: node backend/server.js
    plan: free
    autoDeploy: true
